# The SSH options are passed verbatim to paramiko; see
# https://www.paramiko.org/ This is common CIJOE infrastructure
#
# Used by: cijoe.run() / cijoe.get() / cijoe.put()
[cijoe.transport.qemu_guest]
username = "root"
password = "root"
hostname = "localhost"
port = 4200

[cijoe.workflow]
fail_fast=true

# Used by: the qemu.*.py scripts
[qemu]
img_bin = "qemu-img"

[qemu.systems.x86_64]
bin = "qemu-system-x86_64"

# Used by: qemu.guest_initialize.py, qemu.guest_start.py, and qemu.guest_kill.py
[qemu.guests.generic-bios-kvm-x86_64]
path = "{{ local.env.HOME }}/guests/generic-bios-kvm-x86_64"

# Label of the qemu-system emulerator to use; see "qemu.systems"
system_label = "x86_64"

# Keyword arguments: joined onto the form: "-cpu host -smp 4 -m 4" etc.
system_args.kwa = {cpu = "host", smp = 8, m = "12G", accel = "kvm"}

# Raw arguments: passed without modification to qemu-system-{arch}
system_args.raw = """\
-M "type=q35,kernel_irqchip=split" \
-device "intel-iommu,pt=on,intremap=on" \
"""

# TCP_FORWARD: Setup ssh forward from host to guest
#
# This is is a "special" argument, managed by the cijoe qemu-wrapper,
# specifically by 'guest.start_guest()'
system_args.tcp_forward = {host = 4200, guest = 22}

# SYSTEM_IMAGING: A collection of system images in the form of cloudimages,
# diskimages, and docker images.
#
[system-imaging.images.fedora-40-x86_64]
system_label = "x86_64"

cloud.url ="https://mirror.netsite.dk/fedora/linux/releases/40/Cloud/x86_64/images/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2"
cloud.path = "{{ local.env.HOME }}/system_imaging/cloud/Fedora-Cloud-Base-Generic.x86_64-40-1.14.qcow2"
cloud.metadata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-metadata'] }}"
cloud.userdata_path = "{{ resources.auxiliary['system_imaging.cloudinit-linux-common-userdata'] }}"

disk.path = "/__w/spdk-ci/spdk-ci/fedora_40_x86_64.qcow2"
